#!/bin/sh
json=$1/input.json
[ -f $json ] || json=/rundir/input.json
dir=`dirname $json`
stdout=$dir/stdout.log
stderr=$dir/stderr.log
/gimsatul/gimsatul $json --threads=64 -r 1>$stdout 2>$stderr
status=$?
cat<<EOF
{
  "return_code": $status,
  "artifacts": {
    "stdout_path": "$stdout",
    "stderr_path": "$stderr"
  }
}
EOF
exit $status
